# Generated by Django 4.0.6 on 2022-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='价格')),
                ('lever', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=1, verbose_name='状态')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
